'use client';
import { useMemo, useState } from 'react';

const dentists = [
  { name: 'Dr. Sofia Benali', specialty: 'General dentistry · 12 years', initials: 'SB', color: '#d8e7ff', accent: '#28548a' },
  { name: 'Dr. Adam Naciri', specialty: 'Cosmetic dentistry · 9 years', initials: 'AN', color: '#dcefe7', accent: '#23654f' },
  { name: 'Dr. Maya El Idrissi', specialty: 'Pediatric dentistry · 14 years', initials: 'ME', color: '#f8e3d2', accent: '#a25427' },
];
const times = ['09:00 AM', '10:30 AM', '12:00 PM', '02:00 PM', '03:30 PM', '05:00 PM'];
const dates = [{ day: 'MON', date: '15' }, { day: 'TUE', date: '16' }, { day: 'WED', date: '17' }, { day: 'THU', date: '18' }, { day: 'FRI', date: '19' }];

export default function Home() {
  const [dentist, setDentist] = useState(0); const [date, setDate] = useState(1); const [time, setTime] = useState('10:30 AM'); const [done, setDone] = useState(false);
  const selected = useMemo(() => dentists[dentist], [dentist]);
  if (done) return <main className="shell"><nav><div className="brand"><span className="brandmark">✦</span> clara</div><span className="secure">● Secure booking</span></nav><section className="success"><div className="check">✓</div><p className="eyebrow">Appointment confirmed</p><h1>You’re all set.</h1><p className="muted">We’ve saved your appointment with {selected.name}.</p><div className="receipt"><div><span>DATE</span><strong>Wed, June {dates[date].date}, 2025</strong></div><div><span>TIME</span><strong>{time}</strong></div><div><span>LOCATION</span><strong>Clara Dental · Casablanca</strong></div></div><button className="secondary" onClick={() => setDone(false)}>Book another appointment</button></section></main>;
  return <main className="shell"><nav><div className="brand"><span className="brandmark">✦</span> clara</div><div className="navlinks"><span>How it works</span><span>For patients</span><button className="login">Sign in</button></div></nav><section className="hero"><div><p className="eyebrow">Your smile, on your schedule</p><h1>Dental care<br /><em>made easy.</em></h1><p className="intro">Find a trusted dentist and book an appointment in a few simple steps.</p></div><div className="hero-art"><div className="sun"></div><div className="tooth">✦</div><div className="art-note">Good care starts<br /><b>with a little time.</b></div></div></section><section className="booking"><div className="section-head"><div><p className="eyebrow">01 — Choose your care</p><h2>Who would you like to see?</h2></div><span className="step">Step 1 of 3</span></div><div className="doctor-grid">{dentists.map((d, i) => <button key={d.name} className={`doctor ${dentist === i ? 'selected' : ''}`} onClick={() => setDentist(i)}><div className="avatar" style={{background:d.color,color:d.accent}}>{d.initials}</div><div className="doctor-copy"><strong>{d.name}</strong><span>{d.specialty}</span></div><div className="radio">{dentist === i ? '✓' : ''}</div></button>)}</div><div className="section-head date-head"><div><p className="eyebrow">02 — Pick a time</p><h2>When works for you?</h2></div></div><div className="date-row">{dates.map((d, i) => <button key={d.date} className={`date ${date === i ? 'active' : ''}`} onClick={() => setDate(i)}><span>{d.day}</span><strong>{d.date}</strong><small>JUN</small></button>)}</div><div className="times">{times.map(t => <button key={t} className={time === t ? 'time active' : 'time'} onClick={() => setTime(t)}>{t}</button>)}</div><div className="details"><div><p className="eyebrow">03 — Your details</p><h2>Almost there.</h2></div><div className="form"><input placeholder="Full name" /><input placeholder="Email address" type="email" /><button className="primary" onClick={() => setDone(true)}>Confirm appointment <span>→</span></button></div></div></section><footer><span>© 2025 Clara Dental</span><span>Care that fits your life.</span></footer></main>;
}
